// <auto-generated />
namespace Reston.Pinata.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class seeder_insurance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seeder_insurance));
        
        string IMigrationMetadata.Id
        {
            get { return "201802210405588_seeder_insurance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
